name: BungeeGuard
version: ${project.version}
description: Plugin which adds a security token to the BungeeCord handshaking protocol
author: Luck

main: me.lucko.bungeeguard.backend.BungeeGuardBackendPlugin
softdepend: [ProtocolLib]
api-version: 1.13

commands:
  bungeeguard:
    description: Reloads the configuration
    permission: bungeeguard.reload
    usage: /bungeeguard reload